neutrals:
  type: 'php:8.4'
  source:
    root: scheinman-neutrals-web
  dependencies:
    php:
      composer/composer: '^2.1'
  runtime:
    extensions:
      - apcu
  variables:
    php:
      display_errors: Off
      display_startup_errors: Off
  disk: 2048
  mounts:
    '/web/sites/default/files':
      source: local
      source_path: 'files'
    '/tmp':
      source: local
      source_path: 'tmp'
    '/private':
      source: local
      source_path: 'private'
    '/.drush':
      source: local
      source_path: 'drush'
    '/drush-backups':
      source: local
      source_path: 'drush-backups'
    '/data':
      source: local
      source_path: 'data'
  build:
    flavor: none
  hooks:
    build: |
      set -e
      echo "IyBodHRwczovL2RvY3MucGxhdGZvcm0uc2gvZ3VpZGVzL2RydXBhbC9kZXBsb3kvY3VzdG9taXplLmh0bWwjZW52aXJvbm1lbnQKaWYgWyAtbiAiJFBMQVRGT1JNX0FQUF9ESVIiIC1hIC1mICIkUExBVEZPUk1fQVBQX0RJUiIvY29tcG9zZXIuanNvbiBdIDsgdGhlbgogIGJpbj0kKGNvbXBvc2VyIGNvbmZpZyBiaW4tZGlyIC0td29ya2luZy1kaXI9IiRQTEFURk9STV9BUFBfRElSIiAtLW5vLWludGVyYWN0aW9uIDI+L2Rldi9udWxsKQogIGV4cG9ydCBQQVRIPSIke1BMQVRGT1JNX0FQUF9ESVJ9LyR7YmluOi12ZW5kb3IvYmlufToke1BBVEh9IgpmaQ==" | base64 -d - > .environment
      composer --no-dev --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
    # TODO: Review https://github.com/ilrWebServices/platformsh/edit/main/platformsh_generate_drush_yml.php and compare to https://github.com/platformsh-templates/drupal11/blob/master/drush/platformsh_generate_drush_yml.php
    deploy: |
      set -e
      curl -sS https://raw.githubusercontent.com/ilrWebServices/platformsh/8fd5d3/platformsh_generate_drush_yml.php | php > ~/.drush/drush.yml
      drush deploy
  web:
    locations:
      '/':
        root: 'web'

        # How long to allow static assets from this location to be cached.
        #
        # Can be a time in seconds, or -1 for no caching. Times can be
        # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
        # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
        # 365 days).
        expires: 1d

        # Whether to forward disallowed and missing resources from this
        # location to the application.
        #
        # Can be true, false or a URI path string.
        passthru: '/index.php'

        # Deny access to static files in this location.
        allow: false

        # Rules for specific URI patterns.
        rules:
          # Allow access to common static files.
          '\.(avif|webp|jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
            allow: true
          '^/robots\.txt$':
            allow: true
          '^/sitemap\.xml$':
            allow: true

          # Deny direct access to configuration files.
          '^/sites/sites\.php$':
            scripts: false
          '^/sites/[^/]+/settings.*?\.php$':
            scripts: false

      '/sites/default/files':
        # Allow access to all files in the public files directory.
        allow: true
        expires: 5m
        passthru: '/index.php'
        root: 'web/sites/default/files'

        # Do not execute PHP scripts.
        scripts: false

        rules:
          # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
          '^/sites/default/files/(css|js)':
            expires: 2w

  # Set the timezone for cron jobs.
  timezone: "America/New_York"

  # The configuration of scheduled execution.
  crons:
    drupal:
      # Run drush cron every hour
      spec: '0 * * * *'
      cmd: 'drush core-cron'
employee-data:
  type: 'php:8.4'
  source:
    root: employee-data
  dependencies:
    php:
      composer/composer: '^2.1'
  runtime:
    extensions:
      - apcu
      - ldap
  variables:
    env:
      # This is used by the cron entries and scripts.
      OUTPUT_DIR: "/app/web/data"
  disk: 1024
  timezone: "America/New_York"
  mounts:
    '/web/data':
      source: local
      source_path: 'data'
    '/tmp':
      source: tmp
  web:
    locations:
      '/':
        root: 'web'
        expires: 1d
        passthru: '/index.php'
        allow: false
      '/data':
        root: 'web/data'
        expires: 5m
        passthru: '/index.php'
        allow: true
        scripts: false
        index:
          - "employee-feed.csv"
          - "employee-position-feed.csv"
  build:
    flavor: none
  hooks:
    build: |
      set -e
      echo "IyBodHRwczovL2RvY3MucGxhdGZvcm0uc2gvZ3VpZGVzL2RydXBhbC9kZXBsb3kvY3VzdG9taXplLmh0bWwjZW52aXJvbm1lbnQKaWYgWyAtbiAiJFBMQVRGT1JNX0FQUF9ESVIiIC1hIC1mICIkUExBVEZPUk1fQVBQX0RJUiIvY29tcG9zZXIuanNvbiBdIDsgdGhlbgogIGJpbj0kKGNvbXBvc2VyIGNvbmZpZyBiaW4tZGlyIC0td29ya2luZy1kaXI9IiRQTEFURk9STV9BUFBfRElSIiAtLW5vLWludGVyYWN0aW9uIDI+L2Rldi9udWxsKQogIGV4cG9ydCBQQVRIPSIke1BMQVRGT1JNX0FQUF9ESVJ9LyR7YmluOi12ZW5kb3IvYmlufToke1BBVEh9IgpmaQ==" | base64 -d - > .environment
      composer --no-dev --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
  crons:
    # Run workday-based employee feed generator every 6 hours.
    employee-feed:
      spec: '0 */6 * * *'
      cmd: |
        set -e
        if [ "$PLATFORM_ENVIRONMENT_TYPE" = production ]; then
          cd employee-data/
          php ./build_people_feed.php
        fi
