"https://neutrals.{default}/":
  type: upstream
  upstream: "neutrals:http"
  cache:
    enabled: false
"https://employee-data.{default}/":
  type: upstream
  upstream: "employee-data:http"
  cache:
    enabled: false
